"""empty message

Revision ID: eb7da8726d04
Revises: 
Create Date: 2024-07-15 12:08:48.694191

Doc: https://alembic.sqlalchemy.org/en/latest/tutorial.html#create-a-migration-script
"""
import sqlalchemy as sa
from alembic import op

revision = "eb7da8726d04"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("record_data", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_records")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("records")
    # ### end Alembic commands ###
